logging:
    level:
        web: DEBUG
        org.springframework.security: DEBUG
server:
    port: 8080
spring:
    profiles:
        active: default
    application:
        name: spring-boot-azka-cake-Project
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: fahmifadilah25
        url: jdbc:mysql://localhost:3306/azka_cake
        username: fajar_code
    flyway:
        enabled: true
        locations: classpath:db/migration
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format-sql: true
        show-sql: true
springdoc:
    swagger-ui:
        path: /azkacake/index.html
        operationsSorter: method